"""add messages_json to chats

Revision ID: 38ffa05e5bc6
Revises: 012234eb1c33
Create Date: 2025-06-19 06:36:57.458538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38ffa05e5bc6'
down_revision: Union[str, None] = '012234eb1c33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('messages_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'messages_json')
    # ### end Alembic commands ###
